import "./globals.css";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import MainNavigation from "./components/layout/main-navigation";
import Layout from "./components/layout/layout";
import NotificationProvider from "../../store/notification-context";

const inter = Roboto({
  weight: ["100", "300", "400", "700"],
  subsets: ["cyrillic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NotificationProvider>
          {" "}
          <Layout>
            <main>{children}</main>
          </Layout>
        </NotificationProvider>
      </body>
    </html>
  );
}
